# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/134n-NsYj92e4X-rcv75D0XAswn9bh42B
"""

from entidades import Paciente
from persistencia import GestorDatos


def menu():

    # Cargar datos desde CSV
    lista_pacientes = GestorDatos.cargar_pacientes(Paciente)

    while True:

        print("\n--- MENÚ HOSPITAL ---")
        print("1. Agregar paciente")
        print("2. Mostrar pacientes")
        print("3. Salir")

        opcion = input("Seleccione: ")

        if opcion == "1":

            nombre = input("Nombre: ")

            try:
                edad = int(input("Edad: "))
                peso = float(input("Peso: "))
                altura = float(input("Altura: "))

            except ValueError:
                print("Edad, peso y altura deben ser números.")
                continue

            dni = input("DNI: ")

            p = Paciente(nombre, edad, dni, peso, altura)

            lista_pacientes.append(p)

            print("Paciente agregado correctamente.")

        elif opcion == "2":

            if len(lista_pacientes) == 0:
                print("No hay pacientes registrados.")

            else:
                for p in lista_pacientes:
                    print(p)

        elif opcion == "3":

            # Guardar datos antes de salir
            GestorDatos.guardar_pacientes(lista_pacientes)

            print("Datos guardados correctamente.")
            break

        else:
            print("Opción inválida")


# Ejecutar programa
menu()
